# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newdump_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDump_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 181)
        Dialog.setSizeGripEnabled(False)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 30, 401, 121))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_phone = QtWidgets.QLabel(self.widget)
        self.label_phone.setTextFormat(QtCore.Qt.AutoText)
        self.label_phone.setObjectName("label_phone")
        self.gridLayout.addWidget(self.label_phone, 0, 0, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 0, 1, 1, 2)
        self.label_gmail = QtWidgets.QLabel(self.widget)
        self.label_gmail.setObjectName("label_gmail")
        self.gridLayout.addWidget(self.label_gmail, 1, 0, 1, 1)
        self.lineEdit_gmail = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_gmail.setObjectName("lineEdit_gmail")
        self.gridLayout.addWidget(self.lineEdit_gmail, 1, 1, 1, 2)
        self.label_pass = QtWidgets.QLabel(self.widget)
        self.label_pass.setObjectName("label_pass")
        self.gridLayout.addWidget(self.label_pass, 2, 0, 1, 1)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.gridLayout.addWidget(self.lineEdit_pass, 2, 1, 1, 2)
        self.button_ok = QtWidgets.QPushButton(self.widget)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 3, 1, 1, 1)
        self.button_cancel = QtWidgets.QPushButton(self.widget)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 3, 2, 1, 1)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_phone.setText(_translate("Dialog", "Enter phone number(without +):"))
        self.label_gmail.setText(_translate("Dialog", "Enter Gmail:"))
        self.label_pass.setText(_translate("Dialog", "Enter Gmail Password:"))
        self.button_ok.setText(_translate("Dialog", "Ok"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_NewDump_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
